spring:
  datasource:
    url: jdbc:h2:file:./h2data/java-spring-boot-example-application-h2
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    enabled: true
