server:
  servlet:
    context-path: /api
  port: 9000

spring:
  application:
    name: java-spring-boot-example
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: false
    change-log: classpath:migration/liquibase-changelog.xml

app:
  security:
    jwtSecret: PLACEHOLDER
    jwtExpirationMs: 1000000
    jwtRefreshExpirationMs: 1000000
